### ISSUE TITLE
Mouse move event can cause the dialog the widget is contained in to be moved rather than changing the colour

### ISSUE THREAD

**Issue by damiandixon** [mamontov-cpp/qt-palette-color-picker#2]
Mouse move event can cause the dialog the widget is contained in to be moved rather than changing the colour

You may wish to add a return after calling handleMouseEvents as shown below.
```
void gui::colorpicker::ColorPicker::mouseMoveEvent(QMouseEvent* e)
{
    if (e->buttons() & Qt::LeftButton)
    {
        this->handleMouseEvents(e);
        return ;
    }
    this->QWidget::mouseMoveEvent(e);
}
```

Environment: ArchLinux, KDE, Qt 5.15.2

Nice simple widget. Thanks.

**Comment by mamontov-cpp** [comment]
Thank you for pointing out! I'll fix it ASAP.

**Comment by mamontov-cpp** [comment]
Added fix for the issue. Closing this issue. Re-open and let me know if you need something else.
